language: node_js
node_js: stable
cache: yarn

install:
  - yarn

script:
  - yarn workspace @gallop/test-example run build

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: packages/test-example/dist
  on:
    branch: master