sudo: false

language: node_js
node_js: stable

branches:
  only:
  - master

cache: yarn

before_install:

install:
  - yarn

before_script:

script:
  - yarn run coveralls

after_success:
after_failure:
after_script:

before_deploy:

deploy: